// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MEM2.Data.MEM2
{
    public partial class Evento
    {
        public Evento()
        {
            Notificacao = new HashSet<Notificacao>();
            Seguidos = new HashSet<Seguidos>();
        }

        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Titulo { get; set; }
        public string Categoria { get; set; }
        public DateTime Inicio { get; set; }
        public DateTime Fim { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }

        public virtual ICollection<Notificacao> Notificacao { get; set; }
        public virtual ICollection<Seguidos> Seguidos { get; set; }
    }
}