// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MEM2.Data.MEM2
{
    public partial class Gostos
    {
        public string FkUtilizadorId { get; set; }
        public int PkGostos { get; set; }
        public string Gostos1 { get; set; }

        public virtual AspNetUsers FkUtilizador { get; set; }
    }
}