// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MEM2.Data.MEM2
{
    public partial class Notificacao
    {
        public int Id { get; set; }
        public string FkUtilizadorId { get; set; }
        public int FkEventoId { get; set; }
        public DateTime Hora { get; set; }

        public virtual Evento FkEvento { get; set; }
        public virtual AspNetUsers FkUtilizador { get; set; }
    }
}